void setupNTP();
void updateNTP();
String getClock();
String getDate();
String getTimestamp();
String getTimelog();
String getHourStr();
String getMinStr();
String getSecStr();
String getDayStr();
String getMonthStr();
String getYearStr();
bool validClock();
unsigned int getHourInt();
unsigned int getMinInt();
unsigned int getSecInt();
unsigned int getDayInt();
unsigned int getMonthInt();
unsigned int getYearInt();
